version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8553:8553"
    command: uvicorn app.main:app --reload --port 8553 --host 0.0.0.0
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: "8080"
      HTTPS_METHOD: redirect
      PROXY_ADDRESS_FORWARDING: "true" # <==== very important if you use reverse proxy

networks:
  default:
    external:
      name: nginx-proxy
